use practice;
select * from customer_shopping;
show tables;

rename table customer_shopping_behavior_cleaned to customer_shopping;

-- Q1.total revenue generated by male vs female customer
select gender,sum(purchase_amount) as revenue from customer_shopping group by gender;

-- Q2.which customers used a discount but still spent more than the average purchase amount?
select  customer_id,purchase_amount from customer_shopping where discount_applied="yes" and purchase_amount >=
(select avg(purchase_amount) from customer_shopping);

-- Q3.top 5 products with the highest average rating
select item_purchased,round(avg(review_rating),2) as avg_rating from customer_shopping
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Q4.COMPARE THE AVERAGE PURCHASE AMOUNTS BETWEEN STANDARD AND EXPRESS SHIPPING
select shipping_type,avg(purchase_amount)
from customer_shopping
where shipping_type in ("standard","express")
group by shipping_type;

-- Q5.do subscribed customers spend more? compare average spend and total revenue between sub and non-subs
select subscription_status,
sum(purchase_amount) as total_revenue,
avg(purchase_amount) as avg_amount,
count(customer_id) as total_customers
from customer_shopping
group by subscription_status;

-- Q6.which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
round(100* sum(case when discount_applied="yes" then 1 else 0 end)/count(*),2) as discount_rate
from customer_shopping
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7.segment customers into new , returning, and loyal based on their total number of previous purchases,show the count of each segment.
with customer_types as (
select customer_id,previous_purchases,
case
	when previous_purchases = 1 then "new" 
    when previous_purchases between 2 and 10 then "returning"
    else "loyal"
    end as customer_segment
    from customer_shopping)
select customer_segment,count(*) from customer_types
group by customer_segment;

-- Q8. what are the top 3 most purchased products within each category?
with temp as (select category,item_purchased,count(*) as total_orders,
dense_rank() over(partition by category order by count(*) desc) as rnk from customer_shopping group by category,item_purchased)
select category,item_purchased,total_orders,rnk from temp
where rnk <=3;

-- Q9.Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe
select subscription_status,count(*)
from customer_shopping 
where previous_purchases > 5
group by subscription_status;

-- Q10.what is the revenue contribution of each group?
select age_group,sum(purchase_amount) as revenue
from customer_shopping 
group by age_group;